import { Filter, SlidersHorizontal } from "lucide-react";

import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import type { QueueItem } from "@/data/queue";
import { issueImportanceLabel, type IssueImportance } from "@/components/issues/issue-importance-menu";
import { issueStatuses } from "@/components/issues/issue-status-menu";
import type { QueueAdvancedFilter } from "./types";

export function QueueFilterMenu({ items, advancedFilter, onAdvancedFilterChange }: { items: QueueItem[]; advancedFilter: QueueAdvancedFilter; onAdvancedFilterChange: (filter: QueueAdvancedFilter) => void }) {
  const teams = [...new Map(items.map((item) => [item.teamKey, item.teamName])).entries()];
  const projects = [...new Map(items.map((item) => [item.projectId, item.projectName])).entries()];
  const count = [advancedFilter.status, advancedFilter.importance, advancedFilter.teamKey, advancedFilter.projectId].filter((value) => value !== "all").length;
  const clear = () => onAdvancedFilterChange({ status: "all", importance: "all", teamKey: "all", projectId: "all" });
  return <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" className="text-muted-foreground" aria-label={count ? `Filter, ${count} active` : "Filter"} />}><Filter /></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuLabel>{count ? `${count} active filter${count === 1 ? "" : "s"}` : "Filter issues"}</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuSub><DropdownMenuSubTrigger>Status</DropdownMenuSubTrigger><DropdownMenuSubContent className="w-44"><DropdownMenuRadioGroup value={advancedFilter.status} onValueChange={(value) => onAdvancedFilterChange({ ...advancedFilter, status: value as QueueAdvancedFilter["status"] })}><DropdownMenuRadioItem value="all">Any status</DropdownMenuRadioItem>{issueStatuses.map((status) => <DropdownMenuRadioItem key={status.value} value={status.value}>{status.label}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuSubContent></DropdownMenuSub><DropdownMenuSub><DropdownMenuSubTrigger>Importance</DropdownMenuSubTrigger><DropdownMenuSubContent className="w-44"><DropdownMenuRadioGroup value={advancedFilter.importance} onValueChange={(value) => onAdvancedFilterChange({ ...advancedFilter, importance: value as QueueAdvancedFilter["importance"] })}><DropdownMenuRadioItem value="all">Any importance</DropdownMenuRadioItem>{(["none", "low", "medium", "high", "urgent"] as IssueImportance[]).map((importance) => <DropdownMenuRadioItem key={importance} value={importance}>{issueImportanceLabel(importance)}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuSubContent></DropdownMenuSub>{teams.length > 1 ? <DropdownMenuSub><DropdownMenuSubTrigger>Team</DropdownMenuSubTrigger><DropdownMenuSubContent className="w-48"><DropdownMenuRadioGroup value={advancedFilter.teamKey} onValueChange={(value) => onAdvancedFilterChange({ ...advancedFilter, teamKey: value })}><DropdownMenuRadioItem value="all">Any team</DropdownMenuRadioItem>{teams.map(([key, name]) => <DropdownMenuRadioItem key={key} value={key}>{name} · {key}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuSubContent></DropdownMenuSub> : null}{projects.length > 1 ? <DropdownMenuSub><DropdownMenuSubTrigger>Project</DropdownMenuSubTrigger><DropdownMenuSubContent className="max-h-72 w-52"><DropdownMenuRadioGroup value={advancedFilter.projectId} onValueChange={(value) => onAdvancedFilterChange({ ...advancedFilter, projectId: value })}><DropdownMenuRadioItem value="all">Any project</DropdownMenuRadioItem>{projects.map(([id, name]) => <DropdownMenuRadioItem key={id} value={id}>{name}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuSubContent></DropdownMenuSub> : null}<DropdownMenuSeparator /><DropdownMenuItem onClick={clear}>Clear advanced filters</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}

export function QueueDisplayMenu({ showDetails, onShowDetailsChange }: { showDetails: boolean; onShowDetailsChange: (show: boolean) => void }) {
  return <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" className="text-muted-foreground" aria-label="Display options" />}><SlidersHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48"><DropdownMenuLabel>Display options</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuCheckboxItem checked={showDetails} onCheckedChange={(checked) => onShowDetailsChange(checked === true)}>Show status details</DropdownMenuCheckboxItem><DropdownMenuCheckboxItem checked={false} disabled>Show estimates</DropdownMenuCheckboxItem></DropdownMenuContent></DropdownMenu>;
}
